name: (prod)Deploy To Cloudflare

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*'

jobs:
  cicd:
    uses: mss-boot-io/mss-boot-admin-antd/.github/workflows/cf.yml@main
    with:
      env: prod
    secrets: 
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}