name: (prod)Deploy To Cloudflare

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  cicd:
    uses: mss-boot-io/mss-boot-admin-antd/.github/workflows/cf.yml@main
    with:
      env: prod
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  release:
    needs: cicd
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: rm -rf config.prod.* && npm build

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

